# Generated by Django 2.2.2 on 2019-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=3000)),
                ('date', models.IntegerField()),
            ],
        ),
    ]
