# Generated by Django 2.2.2 on 2019-06-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190619_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoarewe',
            name='picture',
            field=models.CharField(default='hello', max_length=300),
            preserve_default=False,
        ),
    ]
