# Generated by Django 2.2.2 on 2019-06-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_whoarewe_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whoarewe',
            old_name='picture',
            new_name='pictureUrl',
        ),
    ]
