# Generated by Django 2.2.2 on 2019-06-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190619_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whoarewe',
            old_name='pictureUrl',
            new_name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='http://127.0.0.1:8000/media/Standard_Image.jpg', max_length=300),
            preserve_default=False,
        ),
    ]
